IMP/Fix
JayVora-SerpentCS/SerpentCS_Contributions-v8 pull request #107
Opened 2017-06-05 09:58 UTC by VishalPatelSerpentcs

Improved the code and fixed the issue when first time record is being created then jsignature library was not properly initialized.

2017-06-07 22:03 UTC, JayVora-SerpentCS commented
@MeetSCS ping.

2017-06-09 05:26 UTC, ghost requested changes

2017-06-09 05:26 UTC, ghost commented on web_digital_sign/__manifest__.py
> -        digital signature image for a record.
Replace signature image with only signature.

2017-06-09 05:26 UTC, ghost commented on web_digital_sign/static/description/index.html
> +            <h3 class="oe_slogan">This module provides the functionality to store digital signature image for a record</h3>
signature image -> signature

2017-06-09 05:26 UTC, ghost commented on web_digital_sign/static/src/js/digital_sign.js
> +            $(this.$el[0]).find(".signature > canvas").remove();
$el itself is jquery object so we don't need to wrap it again. We can directly use this.$el.find(".signature")

2017-06-09 05:26 UTC, ghost commented on web_digital_sign/static/src/xml/digital_sign.xml
> +            <div id="signature" class="signature panel-body"></div>
Name of id and class is same.

2017-06-09 05:26 UTC, ghost commented on web_digital_sign/static/src/xml/digital_sign.xml
> +            t-att-height="widget.node.attrs.img_height || widget.node.attrs.height"
Can you please add tabindex attribute on img element ?

2017-06-09 05:26 UTC, ghost commented on web_digital_sign/views/users_view.xml
> +                <label for="signature_image" class="oe_edit_only"/>
Can you please explain this changes ?

2017-06-09 05:26 UTC, ghost commented on web_digital_sign/static/src/js/digital_sign.js
> +            this.$el.find("#signature").attr({"tabindex": "0",'height':"100"});
Tabindex should be added in xml schema.

2017-06-09 06:58 UTC, VishalPatelSerpentcs commented on web_digital_sign/__manifest__.py
> -        digital signature image for a record.
Changes are done.

2017-06-09 06:58 UTC, VishalPatelSerpentcs commented on web_digital_sign/static/description/index.html
> +            <h3 class="oe_slogan">This module provides the functionality to store digital signature image for a record</h3>
Changes are done.

2017-06-09 07:04 UTC, VishalPatelSerpentcs commented on web_digital_sign/static/src/js/digital_sign.js
> +            $(this.$el[0]).find(".signature > canvas").remove();
Done. I have made changes according to where $(this.$el[0]) is defined.

2017-06-09 07:08 UTC, VishalPatelSerpentcs commented on web_digital_sign/static/src/xml/digital_sign.xml
> +            <div id="signature" class="signature panel-body"></div>
Replaced the attribute 'id' with 'class'.

2017-06-09 07:09 UTC, vishal-onnet commented on web_digital_sign/static/src/xml/digital_sign.xml
> +            t-att-height="widget.node.attrs.img_height || widget.node.attrs.height"
Changes are done.

2017-06-12 07:55 UTC, JayVora-SerpentCS commented
guys, are we not done yet?

2017-06-12 09:38 UTC, MeetSCS commented
@JayVora-SerpentCS Travis is failing due to unknown reason. Same Travis issue is faced in other PRs. Need your assistance. I am also looking into it.

2017-06-12 10:40 UTC, merged