[FIX]Fixed the issue of expand.
JayVora-SerpentCS/SerpentCS_Contributions-v8 pull request #408
Opened 2019-12-12 07:25 UTC by drashtipatel24

**Fixed issued**

1. Fixed issued of sing view not render a button. #391 

2.  expand button to display in another views.
     1. Go to list view.
      2. added group-by
      3. Click on kanban view or any other view.
      4. multiple time render views it displays expand button.

3. Improved code for a module.
    1. Many methods directly overwrite without super so we improved this method.
    2. used super called and removed unused method.

2019-12-16 07:42 UTC, JayVora-SerpentCS commented
@parvezqureshi review!

2019-12-16 09:02 UTC, parvezqureshi commented
I reviewed code,  @drashtipatel24 please check following improvement:

1)Remove unnecessary import js file and variable
    1.1)var config = require('web.config')
    1.2)var HEADING_COLUMNS_TO_SKIP_IN_GROUPS = 2
    1.3)var _t = core._t;
2)Please Use "use strict";
3)Please Set import js file in alphabetical order.
4)Please update licence file.

2019-12-16 09:06 UTC, JayVora-SerpentCS commented
code line to code line karo review guru!

2019-12-16 09:16 UTC, parvezqureshi requested changes

2019-12-16 09:16 UTC, parvezqureshi commented on web_groupby_expand/static/src/js/web_groups_expand.js
> +var HEADING_COLUMNS_TO_SKIP_IN_GROUPS = 2
Remove unnecessary variable.

2019-12-16 09:16 UTC, parvezqureshi commented on web_groupby_expand/static/src/js/web_groups_expand.js
Please Use "use strict";

2019-12-16 09:16 UTC, parvezqureshi commented on web_groupby_expand/static/src/js/web_groups_expand.js
> +var AbstractController = require('web.AbstractController');
Please Set import js file in alphabetical order.

2019-12-16 09:53 UTC, parvezqureshi commented
**Code Reviewed.**
Tested in local working correctly.

2019-12-23 09:15 UTC, Kontrolix commented
I test it and it does the job for me.

2019-12-24 11:31 UTC, merged