[14.0] [MIG] sale_product_smart_buttons: Migrated the module in v14.
JayVora-SerpentCS/SerpentCS_Contributions-v8 pull request #517
Opened 2020-11-10 12:06 UTC by Chandresh-SerpentCS

- Module developed by **Pragati Patel**. (Assigned by **Yogesh Mahera**)

2020-11-10 12:10 UTC, Chandresh-SerpentCS commented
@YogeshMahera-SerpentCS Please review the PR. Thanks.

2020-11-25 13:33 UTC, JayVora-SerpentCS commented
Pass this to QA @Chandresh-SerpentCS

2020-11-25 13:46 UTC, Chandresh-SerpentCS commented
@JayVora-SerpentCS Please assign Ready to test label in this PR. I can not set any label in the PR.

2020-11-26 10:10 UTC, ForamSerpentCS requested changes

2020-11-26 10:10 UTC, ForamSerpentCS commented on sale_product_smart_buttons/LICENSE/LICENSE
> +    Copyright (C) 2018-Today Serpent Consulting Services Pvt. Ltd.
2020-Today

2020-11-26 10:10 UTC, ForamSerpentCS commented on sale_product_smart_buttons/__manifest__.py
> +    "auto_install": False,
Here, 'auto_install' can be removed as it has False value by default.

2020-11-26 10:10 UTC, ForamSerpentCS commented on sale_product_smart_buttons/models/product.py
> +        order_lines = self.env["sale.order.line"].search(domain)
No need to define separate variable for domain as it only used at once.

2020-11-30 12:11 UTC, pragati-patel98 commented
@ForamSerpentCS I solved the comments, Can you please review it?

2020-12-01 09:49 UTC, ForamSerpentCS approved these changes

2020-12-01 09:51 UTC, merged