[14.0] [MIG] hr_grade_rank: Migrated the module in v14.
JayVora-SerpentCS/SerpentCS_Contributions-v8 pull request #521
Opened 2020-11-18 13:41 UTC by Chandresh-SerpentCS

- Module developed by **Pragati Patel**. (Assigned by **Yogesh Mahera**)

2020-11-18 13:43 UTC, Chandresh-SerpentCS commented
@YogeshMahera-SerpentCS Please review the PR. Thanks.

2020-11-24 18:19 UTC, JayVora-SerpentCS commented
@YogeshMahera-SerpentCS do spend 10 mins for 1 PR daily.

2020-11-26 09:07 UTC, ForamSerpentCS requested changes

2020-11-26 09:07 UTC, ForamSerpentCS commented on hr_grade_rank/LICENSE/LICENSE
> +    Copyright (C) 2011-TODAY Serpent Consulting Services Pvt. Ltd. (<http://www.serpentcs.com>).
2020-TODAY

2020-11-26 09:07 UTC, ForamSerpentCS commented on hr_grade_rank/models/hr_grade_rank.py
> +from odoo import fields, models, api
Imports should be in alphabetical order.

2020-11-26 09:07 UTC, ForamSerpentCS commented on hr_grade_rank/__manifest__.py
> +    "licence": "AGPL-3",
Exclude recurrence of attribute 'licence'.

2020-11-26 09:07 UTC, ForamSerpentCS commented on hr_grade_rank/__manifest__.py
> +    "auto_install": False,
We can remove 'auto_install' attribute as it has False value by default.

2020-11-30 11:00 UTC, pragati-patel98 commented
@ForamSerpentCS I solved the comments, Can you please review it?

2020-12-01 09:48 UTC, ForamSerpentCS approved these changes

2020-12-01 09:50 UTC, merged