[14.0] [MIG] hr_applicant: Migrated the module in v14.
JayVora-SerpentCS/SerpentCS_Contributions-v8 pull request #522
Opened 2020-11-18 13:42 UTC by Chandresh-SerpentCS

- Module developed by **Pragati Patel**. (Assigned by **Yogesh Mahera**)

2020-11-18 13:43 UTC, Chandresh-SerpentCS commented
@YogeshMahera-SerpentCS Please review the PR. Thanks.

2020-11-25 12:06 UTC, JayVora-SerpentCS commented on hr_applicant/LICENSE/LICENSE
> +    Copyright (C) 2011-Today Serpent Consulting Services Pvt. Ltd.
2020-Today

2020-11-25 12:07 UTC, JayVora-SerpentCS commented on hr_applicant/README.rst
> +==================
use = til 't'

2020-11-26 07:36 UTC, ForamSerpentCS requested changes

2020-11-26 07:36 UTC, ForamSerpentCS commented on hr_applicant/__manifest__.py
> +    "application": True,
We may remove "demo", "test" attributes as not any value has been assigned to it. Here, "auto_install" is by default False, so we may remove it.

2020-11-26 07:36 UTC, ForamSerpentCS commented on hr_applicant/models/training.py
> +                )
Here, We may optimise this as this version may accept the comparison/assignment directly by datetime object.

2020-11-26 07:36 UTC, ForamSerpentCS commented on hr_applicant/models/training.py
> +            rec.write({"state": "approved"})
We can avoid this type of pattern for assignment rather we can use rec.state="approved".

2020-11-26 07:36 UTC, ForamSerpentCS commented on hr_applicant/models/training.py
> +        return True
Here, may no need to return True. Please check for this.

2020-11-26 07:36 UTC, ForamSerpentCS commented on hr_applicant/models/training.py
> +        return True
Same as above, we can change the all state assignment and please check for return True if we can remove it.

2020-11-26 07:36 UTC, ForamSerpentCS commented on hr_applicant/models/training.py
> +            ):
Here, we may compare datetime object directly, please check if we can remove string conversion , we may use fields.Datetime.now() rather using python lib datetime.

2020-11-26 07:36 UTC, ForamSerpentCS commented on hr_applicant/wizard/select_training.py
> +import datetime
Remove import datetime if not used elsewhere.

2020-11-26 07:36 UTC, ForamSerpentCS commented on hr_applicant/wizard/select_training.py
> +from odoo import models, fields, api
Import should be in alphabetical order.

2020-11-26 08:47 UTC, ForamSerpentCS requested changes

2020-11-26 08:47 UTC, ForamSerpentCS commented on hr_applicant/wizard/select_training.py
> +                [("id", "=", self._context.get("active_id"))])
Here, we can define self.env[''] object outside the loop.

2020-11-30 10:53 UTC, pragati-patel98 commented
@ForamSerpentCS  I solved the comments, Can you please review it?

2020-12-01 09:47 UTC, ForamSerpentCS approved these changes

2020-12-01 09:50 UTC, merged