[15.0][MIG]hr_applicant:Migrated V14 to V15
JayVora-SerpentCS/SerpentCS_Contributions-v8 pull request #592
Opened 2022-05-06 05:19 UTC by RohanChristianSCS

2023-05-12 06:59 UTC, JayVora-SerpentCS commented
@pragatipatel-serpentcs please review

2023-05-16 07:44 UTC, pragatipatel-serpentcs commented on hr_applicant/LICENSE/LICENSE
> +    Copyright (C) 2022-Today Serpent Consulting Services Pvt. Ltd.
Please update 2023

2023-05-16 07:45 UTC, pragatipatel-serpentcs commented on hr_applicant/README.rst
> +------------
Good to have same decors '====='

2023-05-16 07:46 UTC, pragatipatel-serpentcs commented on hr_applicant/__init__.py
> +from . import wizard
add new line at end of file

2023-05-16 07:46 UTC, pragatipatel-serpentcs commented on hr_applicant/models/__init__.py
> +from . import training
add line at end of file 
please check in other files also.

2023-07-17 12:08 UTC, JayVora-SerpentCS commented
@RohanChristianSCS Pls see

2023-07-17 16:33 UTC, JayVora-SerpentCS commented
@malaykhamar-serpentcs

2023-07-18 08:42 UTC, MalayKhamar-SerpentCS requested changes

2023-07-18 08:42 UTC, MalayKhamar-SerpentCS commented on hr_applicant/README.rst
> +  Details,Previous Occupation,Education Details,Relatives,Languages,Pervious Travel and Profile Report
Please correct the "previous" spelling. (Pervious Travel)

2023-07-18 08:42 UTC, MalayKhamar-SerpentCS commented on hr_applicant/static/description/index.html
> +                                Pervious Travel
Please correct the "previous" spelling.

2023-07-18 08:42 UTC, MalayKhamar-SerpentCS commented on hr_applicant/models/training.py
> +        comodel="hr.job",
Wrong Attribute comodel. Change it to "comodel_name".

2023-07-18 08:42 UTC, MalayKhamar-SerpentCS commented on hr_applicant/models/training.py
> +        comodel="course.type",
Wrong Attribute comodel. Change it to "comodel_name".

2023-07-18 08:42 UTC, MalayKhamar-SerpentCS commented on hr_applicant/models/hr_app_med_occ.py
> +from logging import warning
Please remove unused Importation : warning

2023-07-18 08:42 UTC, MalayKhamar-SerpentCS commented on hr_applicant/models/training.py
> +                _("End Date should be greated than Start date of Training!")
Please correct the spelling of "greater".

2023-07-18 08:42 UTC, MalayKhamar-SerpentCS commented on hr_applicant/models/training.py
> +                    end_date = rec.training_start_date + datetime.timedelta(
Please check the wronlgy use timedelta. It should import directly from the main datetime library, not from the sub class.
Import Like : 
          from datetime import datetime, timedelta

And then use timedelta. 
Also You have already used the relativedelta , so better we use relativedelta and remove to call additional timedelta.

2023-07-18 08:42 UTC, MalayKhamar-SerpentCS commented on hr_applicant/models/training.py
> +                        "Arrival Date should be less or equal than \
Do not break the warnings with \  , It adds the unwanted spaces.Try with " 
like: 
                raise ValidationError(
                    _(
                        "Arrival Date should be less or equal than "
                        "Start date of Training!"
                    )
                )

2023-07-18 08:42 UTC, MalayKhamar-SerpentCS commented on hr_applicant/models/training.py
> +            if rec.date_of_arrival and rec.date_of_arrival < rec.training_start_date:
Please check the condition of arrival date. It is not matching with the validation message.

2023-07-18 08:42 UTC, MalayKhamar-SerpentCS commented on hr_applicant/models/hr_emp_rel_edu.py
> +            elif self.relative_type in ("Mother", "Sister", "Wife", "Aunty"):
What about "Daughter" ? Add it for Female Gender.

2023-07-18 08:42 UTC, MalayKhamar-SerpentCS commented on hr_applicant/report/report_view.xml
> +        <field name="name">Applicant</field>
Suggestion : Please print and check the pdf report format once.

2023-07-18 08:46 UTC, MalayKhamar-SerpentCS commented
@RohanChristianSCS Please check and update.

2023-07-18 12:58 UTC, MalayKhamar-SerpentCS approved these changes

2023-07-18 13:05 UTC, MalayKhamar-SerpentCS commented
Ok Thanks @RohanChristianSCS . 
@JayVora-SerpentCS Ready for Proceed to the next step.

2023-07-18 13:34 UTC, merged