[16.0] [MIG] Migrated label
JayVora-SerpentCS/SerpentCS_Contributions-v8 pull request #609
Opened 2023-10-11 09:13 UTC by dhaval-serpentcs

2023-10-11 13:14 UTC, Trivedi-Vacha-SerpentCS requested changes

2023-10-11 13:14 UTC, Trivedi-Vacha-SerpentCS commented on label/LICENSE/LICENSE
> +    Copyright (C) 2011-Today Serpent Consulting Services Pvt. Ltd.
```suggestion
    Copyright (C) 2023-Today Serpent Consulting Services Pvt. Ltd.
```

2023-10-11 13:14 UTC, Trivedi-Vacha-SerpentCS commented on label/README.rst
> +==================
keep == till last l of "Label"

2023-10-11 13:14 UTC, Trivedi-Vacha-SerpentCS commented on label/models/label_print.py
> +                template.ref_ir_act_report.unlink()
use inline for loop

2023-10-11 13:14 UTC, Trivedi-Vacha-SerpentCS commented on label/report/dynamic_label.py
> +    def get_data(self, row, columns, ids, model, number_of_copy):
Good if we can optimise this method

2023-10-11 13:14 UTC, Trivedi-Vacha-SerpentCS commented on label/wizard/label_print_wizard.py
> +        for data in self.browse(self.ids):
what is the reason browse self? can't we do for data in self:

2024-05-22 10:08 UTC, dhaval-serpentcs commented
i will improve feedback points and send pr from new branch.

2024-05-22 10:08 UTC, closed without merging