[16.0][MIG] Migrated hr_applicant.
JayVora-SerpentCS/SerpentCS_Contributions-v8 pull request #613
Opened 2023-10-13 11:12 UTC by dhaval-serpentcs

2023-10-16 10:14 UTC, Trivedi-Vacha-SerpentCS requested changes

2023-10-16 10:14 UTC, Trivedi-Vacha-SerpentCS commented on hr_applicant/models/hr_app_rel_edu.py
> +    school_name = fields.Char(string="School Name", size=256)
Remove size=X attribute in Char fields, as it's no longer valid since odoo14 for restricting the size of the strings.

2023-10-16 10:14 UTC, Trivedi-Vacha-SerpentCS commented on hr_applicant/models/hr_app_rel_edu.py
> +    field = fields.Char(string="Major/Field of Education", size=128)
same as above

2023-10-16 10:14 UTC, Trivedi-Vacha-SerpentCS commented on hr_applicant/models/hr_app_rel_edu.py
> +                rec.province = rec.state_id = False
optimise the code.

2023-10-16 10:14 UTC, Trivedi-Vacha-SerpentCS commented on hr_applicant/models/hr_emp_rel_edu.py
> +    place_of_birth = fields.Char(string="Place of Birth", size=128)
Remove size=X attribute in Char fields, as it's no longer valid for restricting the size of the strings.
(https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0)

2023-10-16 10:14 UTC, Trivedi-Vacha-SerpentCS commented on hr_applicant/models/hr_emp_rel_edu.py
> +        if self.birthday and self.birthday >= datetime.today().date():
```suggestion
        if self.birthday and self.birthday >= fields.Date.today():
```

2023-10-16 10:14 UTC, Trivedi-Vacha-SerpentCS commented on hr_applicant/models/hr_emp_rel_edu.py
> +    school_name = fields.Char(string="School Name", size=256)
same as above

2023-10-16 10:14 UTC, Trivedi-Vacha-SerpentCS commented on hr_applicant/models/hr_emp_rel_edu.py
> +    field = fields.Char(string="Major/Field of Education", size=128)
same as above

2023-10-16 10:14 UTC, Trivedi-Vacha-SerpentCS commented on hr_applicant/models/hr_emp_trav_lang.py
> +    location = fields.Char(string="Location", size=128, required=True)
same as above

2023-10-16 10:14 UTC, Trivedi-Vacha-SerpentCS commented on hr_applicant/models/hr_recruitment.py
> +    # def fields_view_get(
remove unused code

2023-10-16 10:14 UTC, Trivedi-Vacha-SerpentCS commented on hr_applicant/models/hr_recruitment_employee.py
> +    lang_ids = fields.One2many("employee.language", "employee_id", "Language Ref.")
check the comments on HrEmployeePrivate in hr module
https://github.com/odoo/odoo/blob/16.0/addons/hr/models/hr_employee.py#L20

2023-10-16 10:14 UTC, Trivedi-Vacha-SerpentCS commented on hr_applicant/models/training.py
> +                if attendee.state not in [
optimise the code use inline

2024-05-13 11:59 UTC, Vandan-Pandeji-SerpentCS commented
@dhaval-serpentcs Once you are available, please work on feedback points.

2024-05-22 07:22 UTC, dhaval-serpentcs commented
i will improve feedback points and send pr form new branch.

2024-05-22 07:22 UTC, closed without merging