[MIG] [17.0] import_export_templating: migrated module.
JayVora-SerpentCS/SerpentCS_Contributions-v8 pull request #647
Opened 2024-09-12 07:37 UTC by ShwetaSerpentCS

2024-09-12 08:25 UTC, ketanserpentcs commented
Testing is assigned to Pooja

2024-09-13 12:50 UTC, Trivedi-Vacha-SerpentCS commented on import_export_templating/__manifest__.py
> +    # "assets": {
what commented the code?

2024-09-13 12:53 UTC, Trivedi-Vacha-SerpentCS commented on import_export_templating/wizard/wiz_download_template.py
> +            model = self._context.get("active_model")
`model = self._context.get("active_model") 

if model:`

2024-09-13 13:07 UTC, Trivedi-Vacha-SerpentCS requested changes
@ShwetaSerpentCS I can see scope of code optimisation, can assign to someone familiar with excel report

2024-09-16 05:50 UTC, ShwetaSerpentCS commented
> @ShwetaSerpentCS I can see scope of code optimisation, can assign to someone familiar with excel report

I'm assigning to Ankit vaja.  @Trivedi-Vacha-SerpentCS

2024-10-15 08:31 UTC, ketanserpentcs commented
Testing has been done with index by Pooja

2024-10-15 09:39 UTC, Trivedi-Vacha-SerpentCS approved these changes

2024-10-15 13:41 UTC, merged