[MIG] [17.0] label: migrated module.
JayVora-SerpentCS/SerpentCS_Contributions-v8 pull request #648
Opened 2024-09-12 08:49 UTC by ShwetaSerpentCS

Responsible : Deepak

2024-09-12 08:54 UTC, ketanserpentcs commented
Testing is assigned to Pooja

2024-09-13 09:18 UTC, Trivedi-Vacha-SerpentCS requested changes

2024-09-13 09:18 UTC, Trivedi-Vacha-SerpentCS commented on label/models/label_config.py
> +    top_margin = fields.Float("Top Margin (in mm)", default=0.0)
no need to define default=0.0, by default value of float it will automatically take 0.0

2024-09-13 09:18 UTC, Trivedi-Vacha-SerpentCS commented on label/models/label_config.py
> +    def create(self, vals_list):
missing docstring

2024-09-13 09:18 UTC, Trivedi-Vacha-SerpentCS commented on label/models/label_config.py
> +            if vals.get('height') == 0.0 or vals.get('width') == 0.0:
```suggestion
            if any(vals.get(field) == 0.0 for field in ['height', 'width']):
```

2024-09-13 09:18 UTC, Trivedi-Vacha-SerpentCS commented on label/models/label_config.py
> +        if vals.get('height') == 0.0 or vals.get('width') == 0.0:
same as above

2024-09-13 09:18 UTC, Trivedi-Vacha-SerpentCS commented on label/models/label_print.py
> +    def onchange_model(self):
missing docstring

2024-09-19 11:14 UTC, ShwetaSerpentCS commented
@Trivedi-Vacha-SerpentCS Please review updated code.

2024-11-27 10:42 UTC, ketanserpentcs commented
QA done with index by Pooja

2024-11-27 10:46 UTC, JayVora-SerpentCS commented
@Trivedi-Vacha-SerpentCS @Murtaza-SerpentCS pls review

2024-11-27 10:48 UTC, Trivedi-Vacha-SerpentCS requested changes
missing docstring in methods

2024-12-17 12:29 UTC, Trivedi-Vacha-SerpentCS approved these changes

2024-12-17 12:30 UTC, merged