[MIG] [17.0] hr_applicant: migrated module.
JayVora-SerpentCS/SerpentCS_Contributions-v8 pull request #649
Opened 2024-09-12 09:22 UTC by ShwetaSerpentCS

2024-10-25 06:39 UTC, Trivedi-Vacha-SerpentCS requested changes

2024-10-25 06:39 UTC, Trivedi-Vacha-SerpentCS commented on hr_applicant/__manifest__.py
> +    "website": "http://www.serpentcs.com",
```suggestion
    "website": "https://www.serpentcs.com",
```

2024-10-25 06:39 UTC, Trivedi-Vacha-SerpentCS commented on hr_applicant/models/training.py
> +    # def _check_training_dup(self):
Remove commented code

2024-10-25 06:39 UTC, Trivedi-Vacha-SerpentCS commented on hr_applicant/models/training.py
> +        # readonly=True,
if this is managed from xml side then remove it from py

2024-10-25 06:39 UTC, Trivedi-Vacha-SerpentCS commented on hr_applicant/wizard/select_training.py
> +    # def _onchange_training_courses(self):
Remove commented code if not require for future use

2024-10-25 06:39 UTC, Trivedi-Vacha-SerpentCS commented on hr_applicant/security/ir.model.access.csv
> +access_applicant_education,applicant.education,model_applicant_education,base.group_system,1,1,1,1
every user having 1111 access??
We should manage the access, like user cannot delete 1110 and office can have delete access 1111
@ShwetaSerpentCS

2024-10-25 06:39 UTC, Trivedi-Vacha-SerpentCS commented on hr_applicant/models/training.py
> +        # states={"draft": [("readonly", False)]},
remove commented code

2024-12-03 08:44 UTC, ketanserpentcs commented
Testing is assigned to Pooja

2024-12-17 12:27 UTC, merged