[MIG] [18.0] hr_grade_rank: migrated module
JayVora-SerpentCS/SerpentCS_Contributions-v8 pull request #656
Opened 2024-10-23 09:59 UTC by ShwetaSerpentCS

2024-10-23 10:21 UTC, ketanserpentcs commented
Testing is assigned to Pooja

2024-10-23 12:16 UTC, Trivedi-Vacha-SerpentCS requested changes

2024-10-23 12:16 UTC, Trivedi-Vacha-SerpentCS commented on hr_grade_rank/views/hr_grade_rank_view.xml
> +    <record id="view_employee_grade_list" model="ir.ui.view">
No need to replace tree with list in the ID of any view. as it may cause issues if define reference of the view based on ID.

2024-10-23 12:16 UTC, Trivedi-Vacha-SerpentCS commented on hr_grade_rank/views/hr_grade_rank_view.xml
> +    <record id="view_employee_rank_list" model="ir.ui.view">
same as above, do not change the view ID

2024-10-23 12:16 UTC, Trivedi-Vacha-SerpentCS commented on hr_grade_rank/views/hr_grade_rank_view.xml
> +    <record id="view_employee_list_grade_rank" model="ir.ui.view">
same as above

2024-10-25 09:01 UTC, Trivedi-Vacha-SerpentCS approved these changes

2024-12-05 09:34 UTC, ketanserpentcs commented
QA done with index by Pooja

2024-12-05 09:56 UTC, merged