[MIG] [18.0] import_export_templating: migrated module
JayVora-SerpentCS/SerpentCS_Contributions-v8 pull request #657
Opened 2024-10-23 10:51 UTC by ShwetaSerpentCS

Responsible : Jayram

2024-10-23 12:24 UTC, Trivedi-Vacha-SerpentCS requested changes
@ShwetaSerpentCS header-logo.png and index.html file requires your attention.
educate the developer too about the same.

2024-10-23 12:24 UTC, Trivedi-Vacha-SerpentCS commented on import_export_templating/wizard/wiz_download_template.py
> +                        print("\n\n model", model)
Remove Print statements

2024-10-23 12:30 UTC, Trivedi-Vacha-SerpentCS commented on import_export_templating/__manifest__.py
>      "maintainer": "Serpent Consulting Services Pvt. Ltd.",
summary should not be blank.
also company website link should be https

2024-10-24 12:29 UTC, ketanserpentcs commented
Testing is assigned to devraj

2024-10-25 09:03 UTC, Trivedi-Vacha-SerpentCS approved these changes

2024-10-25 09:07 UTC, Trivedi-Vacha-SerpentCS commented
@ShwetaSerpentCS Icon should not be like this, the module is for data upload, not for any transportation(import/export).

2024-12-18 06:15 UTC, ketanserpentcs commented
QA done with index by devraj

2024-12-18 06:25 UTC, Trivedi-Vacha-SerpentCS commented
@ShwetaSerpentCS kindly verify index and banner

2024-12-18 11:16 UTC, ShwetaSerpentCS commented
> @ShwetaSerpentCS kindly verify index and banner

Done, Ready to merge. @Trivedi-Vacha-SerpentCS

2024-12-19 07:18 UTC, merged