[MIG] [18.0] partner_credit_limit: migrated module
JayVora-SerpentCS/SerpentCS_Contributions-v8 pull request #658
Opened 2024-10-23 12:08 UTC by ShwetaSerpentCS

Responsible : Jayram

2024-10-25 06:19 UTC, Trivedi-Vacha-SerpentCS requested changes

2024-10-25 06:19 UTC, Trivedi-Vacha-SerpentCS commented on partner_credit_limit/__manifest__.py
> +    'website': 'http://www.serpentcs.com',
```suggestion
    'website': 'https://www.serpentcs.com',
```

2024-10-25 06:19 UTC, Trivedi-Vacha-SerpentCS commented on partner_credit_limit/__manifest__.py
> +    'auto_install': False,
default value is False, no need to define

2024-10-25 06:19 UTC, Trivedi-Vacha-SerpentCS commented on partner_credit_limit/models/sale.py
> +    def create(self, vals):
```
@api.model_create_multi
    def create(self, vals_list):
```

2024-10-30 03:52 UTC, ketanserpentcs commented
Testing is assigned to Devraj

2024-12-18 06:18 UTC, ketanserpentcs commented
QA done with index by Devraj

2024-12-18 06:25 UTC, Trivedi-Vacha-SerpentCS commented
@ShwetaSerpentCS kindly verify index and banner

2024-12-18 08:57 UTC, ShwetaSerpentCS commented
> @ShwetaSerpentCS kindly verify index and banner

Done. Ready to merge. @Trivedi-Vacha-SerpentCS

2024-12-19 07:18 UTC, JayVora-SerpentCS commented
Do we need this module?  
ping me on skype

2024-12-19 08:55 UTC, merged