[MIG] [17.0] web_groupby_expand: migrated module
JayVora-SerpentCS/SerpentCS_Contributions-v8 pull request #661
Opened 2024-10-28 10:13 UTC by ShwetaSerpentCS

Responsible : Adnan

2024-10-29 06:25 UTC, Trivedi-Vacha-SerpentCS requested changes

2024-10-29 06:25 UTC, Trivedi-Vacha-SerpentCS commented on web_groupby_expand/__manifest__.py
> +    "data": [
Remove the blank keys

2024-10-30 03:49 UTC, ketanserpentcs commented
Testing is assigned to Pooja

2024-11-13 09:37 UTC, ShwetaSerpentCS commented
QA done by Pooja.

2024-11-13 09:50 UTC, ketanserpentcs commented
QA done with index by Pooja

2024-11-13 09:57 UTC, merged